stages:
  - build
  - test

variables:
  XCODE_WORKSPACE: "pilot-ci-cd.xcworkspace"
  XCODE_SCHEME: "pilot-ci-cd"
  XCODE_SDK: "iphonesimulator"
  XCODE_DESTINATION: "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro"

build:
  stage: build
  script:
    # - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" clean build | xcpretty -s
    - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" clean build | tee build.log
  only: 
    - master
  artifacts:
    paths:
      - build.log
  tags:
  - CI
  - SSH

.test:
  stage: test
  script:
    - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" test | xcpretty -s
  tags:
  - CI
  - SSH
test Again:
  stage: test
  script:
    - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk "$XCODE_SDK" -destination "$XCODE_DESTINATION" test | xcpretty -s
  tags:
  - CI
  - SSH